### ISSUE TITLE
Problem running 

### ISSUE THREAD

**Issue by aodsupport** [walmat/Off-White-Monitor#14]
#python3 -V
Python 3.4.9

When running "python3 main.py" I am getting the following error, can you advise on what I am doing wrong?

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import ow
  File "/usr/local/src/Off-White-Monitor/ow.py", line 212
    title: "N/A"
         ^
SyntaxError: invalid syntax

**Comment by ma1kels** [comment]
have you solved the problem? have the same and don't know what to do.

**Comment by aodsupport** [comment]
No, I suspect it may be due to the Python version or something missing in my Linux Distro (Cent OS 7.x).  I have no clue how to fix it though.

**Comment by ma1kels** [comment]
How would it look like when it works? Do you know if the Off White page hast to be open then in browser or how will I get the notifications onto my discord?
